id: IDD6E0BFB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:48:27+00:00'
last_modified: '2022-06-08T14:08:30.613587+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC251
  title: སྐྱབས་མགོན་མཁས་བཟང་རིན་པོ་ཆེའི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FEF5:
      image_group_id: I2PD19672
      title: ''
      total_pages: 156
      order: 1
      base_file: FEF5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
