id: P010512
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC251
  title: སྐྱབས་མགོན་མཁས་བཟང་རིན་པོ་ཆེའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    a0502a6d3eb4489a88d4295a571c8c76:
      image_group_id: I2PD19672
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
